### ISSUE TITLE
Negative cooking odds with max upgrades + cape + chem

### ISSUE THREAD

**Issue by PKPenguin321** [TBartl/space-station-13-idle#349]
![image](https://user-images.githubusercontent.com/8345184/89509917-c5a80800-d784-11ea-85c0-48ace5249a32.png)

**Comment by remona-minett** [comment]
Does it have any effect on your items (eg removing regular burgers 15% of the time), or is it simply a visual bug?

**Comment by PKPenguin321** [comment]
No actual effect afaik

**Comment by PKPenguin321** [comment]
Also applies to greytiding failure odds with full upgrade + cape + chem
![image](https://user-images.githubusercontent.com/8345184/89607013-5125a580-d826-11ea-954b-99e240823da7.png)

**Comment by remona-minett** [comment]
I'm not sure if this was patched in one of the latest commits, but making the floor 0% would just solve this.

**Comment by PKPenguin321** [comment]
Cooking was fixed in https://github.com/TBartl/space-station-13-idle/commit/c4b965b574b8098da37881555fcacf48410c060c but greytiding remains bugged afaik

**Comment by deadbender** [comment]
Looks like this is still an issue with greytiding. Basing it off of c4b965b makes it look like a quick fix, I can knock this out tonight probably :D

**Comment by remona-minett** [comment]
Shouldn't be too hard to just set somewhere in the logic a `if < 0 set to 0` or something.
